version: 2
jobs:
  build:
#     working_directory: /app
    environment:
      DOCKER_BUILDKIT: 1
#     docker:
#       - image: docker:18.09.2-dind
    machine: true
    steps:
      - checkout
#       - setup_remote_docker:
#           version: 18.06.0-ce
      - run: docker version
      - run: docker ps
      - run: docker build . -t app
      - run: docker run --rm app
