version: 2
jobs:
  build:
    working_directory: /app
    environment:
      DOCKER_BUILDKIT: 1
    docker:
      - image: docker:18.09.2-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.2-ce
      - run: docker version
      - run: docker ps
